// This file is automatically generated. Do not edit.
#pragma once
extern template CStreamNode createStreamNode(CameraFrame &obj) ;
extern template CStreamNode createStreamNode(ZephyrDebugVideoSource &obj) ;
