// This file is automatically generated. Do not edit.
#pragma once
extern template class ZephyrAudioSource<sq15,320>;
extern template CStreamNode createStreamNode(ZephyrAudioSource<sq15,320> &obj) ;
extern template class SlidingBuffer<float,640,320>;
extern template class DeinterleaveStereo<sf32,320,float,320,float,320>;
extern template class CFFT<cf32,1024,cf32,1024>;
extern template class Gain<sq15,320,sq15,320>;
extern template class Spectrogram<cf32,1024>;
extern template class RealToComplex<float,1024,cf32,1024>;
extern template class Convert<sq15,320,sf32,320>;
extern template class Hanning<float,640,float,1024>;
extern template CStreamNode createStreamNode(SpectrogramDisplay &obj) ;
