// This file is automatically generated. Do not edit.
#ifndef EXTERN_TEMPLATES_APPB_HPP
#define EXTERN_TEMPLATES_APPB_HPP

extern template class ZephyrAudioSource<sq15,320>;
extern template CStreamNode createStreamNode(ZephyrAudioSource<sq15,320> &obj) ;
extern template class SlidingBuffer<float,640,320>;
extern template CStreamNode createStreamNode(SlidingBuffer<float,640,320> &obj) ;
extern template class DeinterleaveStereo<sf32,320,float,320,float,320>;
extern template CStreamNode createStreamNode(DeinterleaveStereo<sf32,320,float,320,float,320> &obj) ;
extern template class CFFT<cf32,1024,cf32,1024>;
extern template CStreamNode createStreamNode(CFFT<cf32,1024,cf32,1024> &obj) ;
extern template class Gain<sq15,320,sq15,320>;
extern template CStreamNode createStreamNode(Gain<sq15,320,sq15,320> &obj) ;
extern template class Spectrogram<cf32,1024>;
extern template CStreamNode createStreamNode(Spectrogram<cf32,1024> &obj) ;
extern template class RealToComplex<float,1024,cf32,1024>;
extern template CStreamNode createStreamNode(RealToComplex<float,1024,cf32,1024> &obj) ;
extern template class Convert<sq15,320,sf32,320>;
extern template CStreamNode createStreamNode(Convert<sq15,320,sf32,320> &obj) ;
extern template class Hanning<float,640,float,1024>;
extern template CStreamNode createStreamNode(Hanning<float,640,float,1024> &obj) ;
extern template CStreamNode createStreamNode(SpectrogramDisplay &obj) ;
#endif // EXTERN_TEMPLATES_APPB_HPP
