#ifndef SELECTOR_IDS_H
#define SELECTOR_IDS_H
// This file is automatically generated. Do not edit.
              
// Selector IDs
#ifdef   __cplusplus
extern "C"
{
#endif



              
#ifdef   __cplusplus
}
#endif
#endif // SELECTOR_IDS_H

