// This file is automatically generated. Do not edit.

#include <cstdint>
#include "app_config.hpp"
#include "stream_platform_config.hpp"
#include "cg_enums.h"
#include "StreamNode.hpp"
#include "cstream_node.h"
#include "IdentifiedNode.hpp"
#include "EventQueue.hpp"
#include "GenericNodes.hpp"


#include "appnodes/CameraFrame.hpp"
#include "nodes/ZephyrDebugVideoSource.hpp"

template CStreamNode createStreamNode(CameraFrame &obj) ;
template CStreamNode createStreamNode(ZephyrDebugVideoSource &obj) ;

// Selector initializations
